@movieServiceURL = https://localhost:5006/movies
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImFkbWluIiwibmJmIjoxNjAyMDU1MjA4LCJleHAiOjE2MDIwNTg4MDgsImlhdCI6MTYwMjA1NTIwOH0.-Q3MuyOfrC2E1pE3o4QRM7siMqd_mLJ1Ywo-68zJSzU
# ================= Movies SERVICE ======================= #
GET {{movieServiceURL}}
content-type: application/json
authorization: Bearer {{accessToken}}
content-type: application/json
