@movieServiceURL = https://localhost:5006/movies
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImFkbWluIiwibmJmIjoxNjAxOTk1NjYzLCJleHAiOjE2MDE5OTkyNjMsImlhdCI6MTYwMTk5NTY2M30.3pJB5Q511KjxIpNbfg8kKtE6jFSuFlaXyPIN0hTFROo
# ================= Movies SERVICE ======================= #
GET {{movieServiceURL}}
content-type: application/json
authorization: Bearer {{accessToken}}
content-type: application/json
